pipeline:
  name: python-app
  identifier: pythonapp
  projectIdentifier: pythonapp
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: gsajwan/sample-app
        build: <+input>
  stages:
    - stage:
        name: build-docker-image
        identifier: builddockerimage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.DockerhubConnector
                    repo: gsajwan/sample-app
                    tags:
                      - latest
                      - "1.0"
                    caching: true
                    dockerfile: app/Dockerfile
                    context: app
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.aks
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
    - stage:
        name: Deploy
        identifier: Deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: pythonappservice
          environment:
            environmentRef: production
            gitBranch: main
            deployToAll: false
            infrastructureDefinitions:
              - identifier: pythonappinfra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
