pipeline:
  identifier: Build_gsajwan_sample_app_1733026498067
  name: Build sample-app
  orgIdentifier: default
  projectIdentifier: pythonapp
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: gsajwan/sample-app
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: runlinter
                  name: run linter
                  spec:
                    command: |-
                      pip install flake8
                      flake8 .
                  timeout: ""
                  type: Run
              - step:
                  identifier: setupvirtualenvironment
                  name: setup virtual environment
                  spec:
                    shell: Sh
                    command: |-
                      python3 -m venv .venv
                      . .venv/bin/activate
                      python3 -m pip install -r requirements.txt
                      python3 -m pip install -e .
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    connectorRef: <+input>.allowedValues(account.DockerhubConnector)
                    repo: gsajwan/sample-app
                    tags:
                      - latest
                    caching: true
                    dockerfile: app/Dockerfile
                    context: app
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          platform:
            os: MacOS
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
